utils::globalVariables(c('continent',
                         'location',
                         'iso_code',
                         'total_cases',
                         'total_cases_per_million',
                         'new_cases',
                         'new_cases_per_million',
                         'new_deaths',
                         'new_cases_smoothed',
                         'new_cases_smoothed_per_million',
                         'total_deaths',
                         'total_deaths_per_million',
                         'new_deaths_smoothed',
                         'new_deaths_smoothed_per_million',
                         'new_vaccinations',
                         'people_fully_vaccinated',
                         'people_fully_vaccinated_per_hundred',
                         'stringency_index',
                         'population',
                         'gdp_per_capita',
                         'median_age',
                         'cardiovasc_death_rate',
                         'diabetes_prevalence',
                         'human_development_index',
                         'people_fully_vaccinated_per_hundred_MA',
                         'Alpha-3 code',
                         'Longitude (average)',
                         'country_code',
                         'tags',
                         'providers',
                         'Latitude (average)'
                         )
)
